/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./components/Reports/Chart.vue')['default']
    GroupCard: typeof import('./components/Cards/GroupCard.vue')['default']
    Header: typeof import('./components/Layout/Header.vue')['default']
    LeaderBoards: typeof import('./components/Reports/LeaderBoards.vue')['default']
    NavHeader: typeof import('./components/Layout/NavHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Layout/Sidebar.vue')['default']
    TopicCard: typeof import('./components/Cards/TopicCard.vue')['default']
    Topics: typeof import('./components/Reports/Topics.vue')['default']
    UserCard: typeof import('./components/Cards/UserCard.vue')['default']
  }
}
